import { Injectable, Logger, ServiceUnavailableException } from '@nestjs/common';
import { PrismaService } from '../../common/prisma.service';
import { AuditService } from '../../common/audit.service';

@Injectable()
export class SuperComplianceService {
  private readonly logger = new Logger(SuperComplianceService.name);
  constructor(private prisma: PrismaService, private audit: AuditService) {}

  async getConfig(configKey?: string) {
    if (!this.prisma.isConnected()) return this.defaultConfig();
    if (configKey) return this.prisma.superComplianceConfig.findUnique({ where: { configKey } });
    return this.prisma.superComplianceConfig.findMany({ orderBy: { category: 'asc' } });
  }

  async setConfig(configKey: string, configValue: any, category: string, description?: string, modifiedBy?: string) {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');
    return this.prisma.superComplianceConfig.upsert({
      where: { configKey },
      update: { configValue, description, modifiedBy, category },
      create: { configKey, configValue, category, description, modifiedBy },
    });
  }

  async createAudit(data: { companyId: string; auditType: string; scope: string; auditorId: string; scheduledDate?: string; priority?: string; notes?: string }) {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');
    const audit = await this.prisma.superComplianceAudit.create({
      data: { ...data, scheduledDate: data.scheduledDate ? new Date(data.scheduledDate) : undefined },
    });
    return audit;
  }

  async getAudits(params?: { companyId?: string; status?: string; auditorId?: string; page?: number; limit?: number }) {
    if (!this.prisma.isConnected()) return { data: [], pagination: { page: 1, limit: 20, total: 0, totalPages: 0 } };
    const page = params?.page || 1; const limit = Math.min(params?.limit || 20, 100); const skip = (page - 1) * limit;
    const where: any = {};
    if (params?.companyId) where.companyId = params.companyId;
    if (params?.status) where.status = params.status.toUpperCase();
    if (params?.auditorId) where.auditorId = params.auditorId;
    const [data, total] = await Promise.all([this.prisma.superComplianceAudit.findMany({ where, skip, take: limit, orderBy: { createdAt: 'desc' } }), this.prisma.superComplianceAudit.count({ where })]);
    return { data, pagination: { page, limit, total, totalPages: Math.ceil(total / limit) } };
  }

  async completeAudit(auditId: string, data: { findings?: string; complianceScore?: number; issuesFound?: number; issuesList?: any[]; companiesCovered?: string[]; actionItems?: any[] }, completedBy: string) {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');
    return this.prisma.superComplianceAudit.update({ where: { id: auditId }, data: { status: 'COMPLETED', completedAt: new Date(), ...data } });
  }

  async createAlert(data: { companyId: string; alertType: string; entityType?: string; entityId?: string; severity: string; title: string; message: string; autoGenerated?: boolean; metadata?: any }) {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');
    return this.prisma.superComplianceAlert.create({ data });
  }

  async getAlerts(params?: { companyId?: string; status?: string; severity?: string; alertType?: string; page?: number; limit?: number }) {
    if (!this.prisma.isConnected()) return { data: [], pagination: { page: 1, limit: 20, total: 0, totalPages: 0 } };
    const page = params?.page || 1; const limit = Math.min(params?.limit || 20, 100); const skip = (page - 1) * limit;
    const where: any = {};
    if (params?.companyId) where.companyId = params.companyId;
    if (params?.status) where.status = params.status.toUpperCase();
    if (params?.severity) where.severity = params.severity.toUpperCase();
    if (params?.alertType) where.alertType = params.alertType;
    const [data, total] = await Promise.all([this.prisma.superComplianceAlert.findMany({ where, skip, take: limit, orderBy: { createdAt: 'desc' } }), this.prisma.superComplianceAlert.count({ where })]);
    return { data, pagination: { page, limit, total, totalPages: Math.ceil(total / limit) } };
  }

  async acknowledgeAlert(alertId: string, acknowledgedBy: string) {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');
    return this.prisma.superComplianceAlert.update({ where: { id: alertId }, data: { status: 'ACKNOWLEDGED', acknowledgedBy, acknowledgedAt: new Date() } });
  }

  async resolveAlert(alertId: string, resolvedBy: string, notes?: string) {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');
    return this.prisma.superComplianceAlert.update({ where: { id: alertId }, data: { status: 'RESOLVED', resolvedBy, resolvedAt: new Date(), resolutionNotes: notes } });
  }

  async getCompanyScore(companyId: string, period?: string) {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');
    const where: any = { companyId };
    if (period) where.period = period;
    const scores = await this.prisma.superComplianceScore.findMany({ where, orderBy: { evaluationDate: 'desc' }, take: 1 });
    return scores[0] || { overallScore: 100 };
  }

  async calculateCompanyScore(companyId: string, period: string) {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');

    const totalDocs = await this.prisma.companyComplianceDoc.count({ where: { companyId } });
    const validDocs = await this.prisma.companyComplianceDoc.count({ where: { companyId, status: 'APPROVED' } });
    const totalVehicles = await this.prisma.vehicleManagement.count({ where: { companyId, status: 'ACTIVE' } });
    const compliantVehicles = await this.prisma.vehicleManagement.count({ where: { companyId, status: 'ACTIVE', insuranceExpiry: { gt: new Date() } } });
    const totalDrivers = await this.prisma.driverManagement.count({ where: { companyId, status: 'ACTIVE' } });
    const totalIssues = await this.prisma.complianceAudit.count({ where: { companyId, actionRequired: true } });
    const resolvedIssues = await this.prisma.complianceAudit.count({ where: { companyId, actionRequired: true, actionTaken: { not: null } } });

    const documentScore = totalDocs > 0 ? (validDocs / totalDocs) * 100 : 100;
    const vehicleScore = totalVehicles > 0 ? (compliantVehicles / totalVehicles) * 100 : 100;
    const overallScore = Math.round(((documentScore + vehicleScore) / 2) * 100) / 100;
    const grade = overallScore >= 90 ? 'A' : overallScore >= 75 ? 'B' : overallScore >= 60 ? 'C' : overallScore >= 40 ? 'D' : 'F';

    const score = await this.prisma.superComplianceScore.upsert({
      where: { companyId_period: { companyId, period } },
      update: { overallScore, documentScore, vehicleScore, totalIssues, resolvedIssues, pendingIssues: totalIssues - resolvedIssues, evaluationDate: new Date() },
      create: { companyId, overallScore, documentScore, vehicleScore, totalIssues, resolvedIssues, pendingIssues: totalIssues - resolvedIssues, period, evaluationDate: new Date() },
    });

    await this.prisma.companyComplianceStanding.upsert({
      where: { companyId },
      update: { overallScore, overallGrade: grade, documentCompliance: documentScore, vehicleCompliance: vehicleScore, totalDocuments: totalDocs, validDocuments: validDocs, totalVehicles, compliantVehicles, totalDrivers, lastAuditDate: new Date(), lastAuditScore: overallScore },
      create: { companyId, overallScore, overallGrade: grade, documentCompliance: documentScore, vehicleCompliance: vehicleScore, totalDocuments: totalDocs, validDocuments: validDocs, totalVehicles, compliantVehicles, totalDrivers, lastAuditDate: new Date(), lastAuditScore: overallScore },
    });

    return score;
  }

  async getAllCompanyStandings() {
    if (!this.prisma.isConnected()) return [];
    return this.prisma.companyComplianceStanding.findMany({ orderBy: { overallScore: 'asc' } });
  }

  async getPlatformRules() {
    if (!this.prisma.isConnected()) return this.defaultRules();
    const rules = await this.prisma.platformComplianceRule.findMany({ where: { isActive: true } });
    return rules.length > 0 ? rules : this.defaultRules();
  }

  async createPlatformRule(data: { ruleCode: string; ruleName: string; category: string; description: string; severity?: string; autoEnforce?: boolean; action?: string; applicableTo?: string; threshold?: any }) {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');
    return this.prisma.platformComplianceRule.create({ data });
  }

  async runPlatformAudit() {
    if (!this.prisma.isConnected()) throw new ServiceUnavailableException('Database unavailable');
    const companies = await this.prisma.company.findMany({ where: { status: 'ACTIVE' }, select: { id: true, name: true } });
    let scanned = 0;
    for (const company of companies) {
      try {
        await this.calculateCompanyScore(company.id, new Date().toISOString().slice(0, 7));
        scanned++;
      } catch (err: any) {
        this.logger.error(`Score calculation failed for ${company.name}: ${err.message}`);
      }
    }
    return { scanned, total: companies.length };
  }

  private defaultConfig() {
    return [
      { configKey: 'MIN_COMPLIANCE_SCORE', configValue: 70, description: 'Minimum compliance score for companies' },
      { configKey: 'AUTO_SUSPEND_THRESHOLD', configValue: 40, description: 'Score below which company gets auto-suspended' },
      { configKey: 'AUDIT_FREQUENCY_DAYS', configValue: 30, description: 'Days between mandatory audits' },
      { configKey: 'DOCUMENT_EXPIRY_ALERT_DAYS', configValue: 30, description: 'Days before expiry to send alerts' },
    ];
  }

  private defaultRules() {
    return [
      { ruleCode: 'DRV-001', ruleName: 'Valid License Required', category: 'DRIVER', description: 'All drivers must have a valid driving license', severity: 'CRITICAL', autoEnforce: true, action: 'SUSPEND' },
      { ruleCode: 'VEH-001', ruleName: 'Valid Insurance Required', category: 'VEHICLE', description: 'All vehicles must have valid insurance', severity: 'CRITICAL', autoEnforce: true, action: 'SUSPEND' },
      { ruleCode: 'VEH-002', ruleName: 'Valid PUC Required', category: 'VEHICLE', description: 'All vehicles must have valid PUC certificate', severity: 'HIGH', autoEnforce: true, action: 'WARNING' },
      { ruleCode: 'VEN-001', ruleName: 'Active Contract Required', category: 'VENDOR', description: 'Vendors must have an active contract', severity: 'HIGH', autoEnforce: false, action: 'ALERT' },
    ];
  }
}